site_name: Code of Copper Docs
repo_url: https://github.com/GMDU/code-of-copper
repo_name: GMDU/code-of-copper
extra_css:
  - overrides/extra.css
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.top
    - navigation.footer
    - navigation.indexes
  custom_dir: docs/overrides
markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
extra:
  parent_site: /
  social:
    - icon: simple/discord
      link: https://discord.gg/8AUCx5exKF
    - icon: simple/github
      link: https://github.com/GMDU
nav:
  - 'index.md'
  - 'syntax.md'
  - 'data_types.md'
  - 'stdlib.md'
  - 'operators.md'
  - 'keywords.md'
  - 'examples.md'
  - 'plugins.md'
